// ignore_for_file: prefer_const_constructors

import 'model.dart';

var listValueKamenRider = [
  Model(name: "Kamen Rider Ichigo - Takeshi Hongo / Takeshi Hongo (reboot)"),
  Model(name: "Kamen Rider Nigo - Hayato Ichimonji / Katsuhiko Yano"),
  Model(name: "Kamen Rider V3 - Shiro Kazami / Shiro Kazami (reboot)"),
  Model(name: "Riderman - Joji Yuki / Joji Yuki (A.R. World)"),
  Model(name: "Kamen Rider X - Keisuke Jin / X-Rider (A.R. World)"),
  Model(name: "Kamen Rider Amazon - Daisuke Yamamoto / Amazon"),
  Model(name: "Kamen Rider Stronger - Shigeru Jo"),
  Model(name: "Skyrider - Hiroshi Tsukuba"),
  Model(name: "Kamen Rider Super-1 - Kazuya Oki"),
  Model(name: "Kamen Rider ZX - Ryo Murasame"),
  Model(
      name: "Kamen Rider Black - Kotaro Minami / Kotaro Minami (A.R. World 2)"),
  Model(
      name:
          "Kamen Rider Black RX - Kotaro Minami / Kotaro Minami (A.R. World)"),
  Model(name: "Kamen Rider Shin - Shin Kazamatsuri"),
  Model(name: "Kamen Rider ZO - Masaru Aso"),
  Model(name: "Kamen Rider J - Kouji Segawa"),
  Model(name: "Kamen Rider Kuuga - Yusuke Godai / Yusuke Onodera"),
  Model(name: "Kamen Rider Agito - Shouichi Tsugami / Shouichi Ashikawa"),
  Model(name: "Kamen Rider G3 - Makoto Hikawa / Shouichi Ashikawa"),
  Model(
      name: "Kamen Rider G3-X - Makoto Hikawa / Shouichi Tsugami / Toru Hojo"),
  Model(name: "Kamen Rider G3 Mild - Takahiro Omuro"),
  Model(name: "Kamen Rider Gills - Ryo Ashihara / Shouichi Ashikawa"),
  Model(name: "Another Agito - Kaoru Kino"),
  Model(name: "V1 - Toru Hojo"),
  Model(name: "Kamen Rider G4 - Shiro Mizuki"),
  Model(name: "Kamen Rider Ryuki - Shinji Kido / Shinji Tatsumi"),
  Model(name: "Kamen Rider Knight - Ren Akiyama / Ren Haguro"),
  Model(
      name:
          "Kamen Rider Scissors - Masashi Sudo / Kamen Rider Scissors (A.R. World)"),
  Model(
      name:
          "Kamen Rider Zolda - Shuichi Kitaoka / Goro Yura / Kamen Rider Zolda (A.R. World)"),
  Model(name: "Kamen Rider Raia - Yuichi Saito / Miyuki Tezuka"),
  Model(name: "Kamen Rider Gai - Jun Shibaura"),
  Model(name: "Kamen Rider Ouja - Takeshi Asakura"),
  Model(
      name: "Kamen Rider Tiger - Satoru Tojo / Kamen Rider Tiger (A.R. World)"),
  Model(
      name:
          "Kamen Rider Imperer - Mitsuru Sano / Kamen Rider Imperer (A.R. World)"),
  Model(name: "Kamen Rider Odin - ? / Kamen Rider Odin (A.R. World)"),
  Model(name: "Alternative Zero - Hideyuki Kagawa / Tanaka"),
  Model(name: "Alternative - Hajime Nakamura / Tanaka"),
  Model(name: "Kamen Rider Femme - Miho Kirishima"),
  Model(name: "Kamen Rider Ryuga - Dark Shinji"),
  Model(
      name:
          "Kamen Rider Verde - Itsuro Takamizawa / Kamen Rider Verde (A.R. World)"),
  Model(name: "Kamen Rider Faiz - Takumi Inui / Takumi Ogami"),
  Model(name: "Kamen Rider Kaixa - Masato Kusaka / Yuji Kiba"),
  Model(name: "Kamen Rider Delta - Shuji Mihara"),
  Model(name: "Kamen Rider Psyga - Leo"),
  Model(name: "Kamen Rider Orga - Yuji Kiba / Kenji Sakata"),
  Model(name: "Kamen Rider Blade - Kazuma Kenzaki / Kazuma Kendate"),
  Model(name: "Kamen Rider Garren - Sakuya Tachibana / Sakuya Hishigata"),
  Model(name: "Kamen Rider Chalice - Hajime Aikawa / Hajime Shijo"),
  Model(name: "Kamen Rider Leangle - Mutsuki Kamijo / Mutsuki Kuroba"),
  Model(name: "Kamen Rider Glaive - Junichi Shimura / Junichi Kaito"),
  Model(name: "Kamen Rider Larc - Natsumi Miwa / Haruka Miwa"),
  Model(name: "Kamen Rider Lance - Shin Magaki / Shin Magaki (A.R. World)"),
  Model(
      name:
          "Kamen Rider Hibiki - Hitoshi Hidaka / Hibiki (A.R. World) / Asumu"),
  Model(name: "Kamen Rider Ibuki - Iori Izumi / Ibuki (A.R. World)"),
  Model(name: "Kamen Rider Todoroki - Tomizo Todayama / Todoroki (A.R. World)"),
  Model(name: "Kamen Rider Zanki - Zaomaru Zaitsuhara / Zanki (A.R. World)"),
  Model(name: "Kamen Rider Danki - Daisuke Danda"),
  Model(name: "Kamen Rider Sabaki - Sakae Saeki"),
  Model(name: "Kamen Rider Eiki - Eiki"),
  Model(name: "Kamen Rider Shouki - Shouki"),
  Model(name: "Kamen Rider Shuki - Shuki"),
  Model(name: "Kamen Rider Amaki - Akira Amami / Akira (A.R. World)"),
  Model(name: "Kamen Rider Kyoki - Kyosuke Kiriya"),
  Model(name: "Kamen Rider Kabuki - Kabuki"),
  Model(name: "Kamen Rider Tohki - Tohki"),
  Model(name: "Kamen Rider Kirameki - Kirameki"),
  Model(name: "Kamen Rider Nishiki - Nishiki"),
  Model(name: "Kamen Rider Habataki - Habataki"),
  Model(name: "Kamen Rider Akatsuki - Tsutomu Tsumura"),
  Model(name: "Kamen Rider Kabuto - Souji Tendou / Souji"),
  Model(
      name:
          "Kamen Rider TheBee - Sou Yaguruma / Arata Kagami / Shun Kageyama / Masato Mishima / Sou Otogiri"),
  Model(name: "Kamen Rider Drake - Daisuke Kazama"),
  Model(name: "Kamen Rider Sasword - Tsurugi Kamishiro"),
  Model(name: "Kamen Rider Gatack - Arata Kagami / Arata"),
  Model(name: "Kamen Rider KickHopper - Sou Yaguruma"),
  Model(name: "Kamen Rider PunchHopper - Shun Kageyama"),
  Model(name: "Kamen Rider Dark Kabuto - Souji Kusakabe / Kazuyoshi Aoyagi"),
  Model(name: "Kamen Rider Caucasus - Issei Kurosaki"),
  Model(name: "Kamen Rider Hercus - Hidenari Oda"),
  Model(name: "Kamen Rider Ketaros - Tetsuki Yamato"),
  Model(name: "Kamen Rider Den-O Sword - Ryotaro Nogami/Momotaros"),
  Model(name: "Kamen Rider Den-O Rod - Ryotaro Nogami/Urataros"),
  Model(name: "Kamen Rider Den-O Ax - Ryotaro Nogami/Kintaros"),
  Model(name: "Kamen Rider Den-O Gun - Ryotaro Nogami/Ryutaros"),
  Model(name: "Kamen Rider Den-O Wing - Ryotaro Nogami/Sieg"),
  Model(name: "Kamen Rider Den-O Liner - Ryotaro Nogami"),
  Model(name: "Kamen Rider Zeronos - Yuto Sakurai"),
  Model(name: "Kamen Rider Zeronos Vega - Yuto Sakurai/Deneb"),
  Model(name: "Kamen Rider Gaoh - Gaoh"),
  Model(name: "Kamen Rider Mini Den-O - Ryotaro (Kotaro) Nogami/Momotaros"),
  Model(name: "Kamen Rider Nega Den-O - Negataros"),
  Model(name: "Kamen Rider Yuuki Skull - Ryotaro Nogami/Ghost Imagin"),
  Model(name: "Kamen Rider Yuuki Hijack - Shiro"),
  Model(name: "Kamen Rider New Den-O Strike - Kotaro Nogami"),
  Model(name: "Kamen Rider G Den-O - Reiji Kurosaki/Eve"),
  Model(name: "Kamen Rider Kiva - Wataru Kurenai / Wataru"),
  Model(
      name:
          "Kamen Rider Ixa - Jiro / Otoya Kurenai / Keisuke Nago / Kamen Rider Ixa (A.R. World)"),
  Model(
      name: "Kamen Rider Saga - Taiga Nobori / Kamen Rider Saga (A.R. World)"),
  Model(name: "Kamen Rider Dark Kiva - King / Otoya Kurenai / Taiga Nobori"),
  Model(name: "Kamen Rider New Kiva - Masao Kurenai"),
  Model(name: "Kamen Rider Rey - Takato Shiramine"),
  Model(name: "Kamen Rider Arc - Takashi Sugimura"),
  Model(name: "Kamen Rider Decade - Tsukasa Kadoya"),
  Model(name: "Kamen Rider Diend - Daiki Kaito"),
  Model(name: "Kamen Rider Abyss - Kamata"),
  Model(name: "Kamen Rider Kiva-la - Natsumi Hikari"),
  Model(name: "Kamen Rider G - Goro"),
  Model(name: "Kamen Rider Double - Philip & Shotaro Hidari"),
  Model(name: "Kamen Rider Accel - Ryu Terui"),
  Model(name: "Kamen Rider Joker - Shotaro Hidari"),
  Model(name: "Kamen Rider Cyclone - Philip"),
  Model(name: "Kamen Rider Skull - Sokichi Narumi"),
  Model(name: "Kamen Rider Eternal - Jun Kazu / Katsumi Daido"),
  Model(name: "Kamen Rider OOO - Eiji Hino"),
  Model(name: "Kamen Rider Birth - Akira Date / Shintaro Goto"),
  Model(name: "Kamen Rider Birth Prototype - Shintaro Goto / Akira Date"),
  Model(name: "Kamen Rider Core - Kamen Rider Core"),
  Model(name: "Kamen Rider Poseidon - Michal Minato / Poseidon"),
  Model(name: "Kamen Rider Aqua - Michal Minato"),
  Model(name: "Kamen Rider Fourze - Gentaro Kisaragi"),
  Model(name: "Kamen Rider Meteor - Ryusei Sakuta"),
  Model(name: "Kamen Rider Nadeshiko - Nadeshiko Misaki"),
  Model(name: "Kamen Rider Wizard - Haruto Soma"),
  Model(name: "Kamen Rider Wiseman - Sou Fueki / Koyomi Fueki"),
  Model(name: "Kamen Rider Beast - Kosuke Nitoh"),
  Model(
      name:
          "Kamen Rider Mage - Mayu Inamori / Yuzuru Iijima / Masahiro Yamamoto / Denizens of Magic Land"),
  Model(name: "Kamen Rider Sorcerer - Minister Orma"),
  Model(name: "Kamen Rider Gaim - Kota Kazuraba"),
  Model(name: "Kamen Rider Baron - Kaito Kumon"),
  Model(name: "Kamen Rider Ryugen - Mitsuzane Kureshima"),
  Model(name: "Kamen Rider Zangetsu - Takatora Kureshima"),
  Model(name: "Kamen Rider Gridon - Hideyasu Jonouchi"),
  Model(name: "Kamen Rider Kurokage - Ryoji Hase"),
  Model(name: "Kamen Rider Bravo - Oren Pierre Alfonzo"),
  Model(name: "Kamen Rider Knuckle - Zack"),
  Model(
      name:
          "Kamen Rider Zangetsu Shin - Takatora Kureshima / Mitsuzane Kureshima"),
  Model(name: "Kamen Rider Duke - Ryoma Sengoku"),
  Model(name: "Kamen Rider Sigurd - Lock Dealer Sid"),
  Model(name: "Kamen Rider Marika - Yoko Minato"),
  Model(name: "Kamen Rider Kurokage Shin - Peco"),
  Model(name: "Kamen Rider Fifteen - Ren Aoi"),
  Model(name: "Kamen Rider Kamuro - Lapis"),
  Model(name: "Kamen Rider Malus - Kogane"),
  Model(name: "Kamen Rider Drive"),
];
